### ISSUE TITLE
meta.abf function with prior.rho specified 

### ISSUE THREAD

**Issue by zhangyd10** [trochet/metabf#1]
Dear Sir/Madam: 

For the function meta.abf, I set prior.cor="correlated" and I want to provide the off-diagonal elements for matrix rho using argument: prior.rho=...

I tried a few common R functions which can get the upper triangular elements of a matrix, but I kept get this error: 

_"prior.rho should be either a flat value or the full upper triangle of the desired correlation matrix"_ 

May I ask what format should prior.rho take? Can you give an example about it? 

Sincerely yours, 
Yidong Zhang

**Comment by trochet** [comment]
> May I ask what format should prior.rho take? Can you give an example about it?

If you're using the upper triangle of a correlation matrix, then `prior.rho` should be a numeric vector of size `choose(n,2)`, when `n` is the number of rows and columns of your correlation matrix.

For simplicity, let's assume your correlation matrix is called `cor.mat`. Then the way I recommend to get the upper triangle for `prior.cor` is
`prior.cor <- cor.mat[which(upper.tri(cor.mat))]`

Let me know how it works out. If it fails, we can continue to troubleshoot.


-Holly

**Comment by trochet** [comment]
> May I ask what format should prior.rho take? Can you give an example about it?

If you're using the upper triangle of a correlation matrix, then `prior.rho` should be a numeric vector of size `choose(n,2)`, where `n` is the number of rows and columns of your correlation matrix.

For simplicity, let's assume your correlation matrix is called `cor.mat`. Then the way I recommend to get the upper triangle for `prior.rho` is
`prior.rho <- cor.mat[which(upper.tri(cor.mat))]`

You can also set the parameter `prior.cor=cor.mat` and leave `prior.rho` undefined.

Let me know how it works out. If it fails, we can continue to troubleshoot.



-Holly

**Comment by zhangyd10** [comment]
Hi, Holly: 

Many thanks for your help. 
I tried both ways you suggested _(directly set prior.cor=cor.mat; prior.rho <- cor.mat[which(upper.tri(cor.mat))])_ . It seems that both methods worked, but sometimes (when the cor.mat is not diagonal) they give different results (ABF).  
Based on my knowledge of my data, I think the result given by setting _prior.cor=cor.mat_ is more reliable. 
Could you have a look at it if convenient? 

Sincerely yours, 
Yidong Zhang

**Comment by trochet** [comment]
Hi Yidong,

You're correct that setting `prior.cor=cor.mat` will give the more accurate answer. I think it's probably easier to remove the option to input an upper triangle into `prior.rho` and instead direct anyone who has a full correlation matrix defined to input it directly. It removes the redundancy and it's hard to imagine a situation where someone would have the upper triangle of a correlation matrix, but not the matrix itself.

Thanks for bringing this to my attention.


-Holly

**Comment by trochet** [comment]
I have (finally) made the necessary changes to the code and documentation, so hopefully this issue won't arise for others.
